# Details
## Install plugin [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

# Environment Switching
@baseUrl = {{$dotenv BASE_URL}}

# Create Transaction
POST {{baseUrl}}/transactions
Content-Type: application/json

{
  "title": "testando",
  "amount": 100,
  "type": "debit"
}

### List All Transactions
GET {{baseUrl}}/transactions
Accept: application/json

### Buscar transação pelo ID
GET {{baseUrl}}/transactions/400d8371-816b-4bd0-a110-51317ad5dee9
Accept: application/json


### Buscar Resumo da conta
GET {{baseUrl}}/transactions/summary
Accept: application/json
